Fix NoneType Attribute error if the connection fails due to a timeout.
$ python ./redfishMockupCreate.py  -u root -p calvin -r 10.10.1.1 -D mocks/ -vvvv -S
   redfishMockupCreate: Transport: Cant connect to remote redfish service. Aborting command
   redfishMockupCreate: Transport Error. No response
Traceback (most recent call last):
  File "./redfishMockupCreate.py", line 820, in <module>
    main(sys.argv)
  File "./redfishMockupCreate.py", line 282, in main
    .format(r.status_code))
AttributeError: 'NoneType' object has no attribute 'status_code'